---
eduid:
  worker:
    common:
      debug: yes
    ladok-x:
      api_server:
        host: :8080
    ladok:
      api_server:
        host: :8080
      production: true
      http_proxy: "some-proxy.se"
      schools:
        kf:
          swamid_name: student.konstfack.se
        lnu:
          swamid_name: lnu.se
        hb:
          swamid_name: hb.se
        ehs:
          swamid_name: ehs.se
      school_information:
        alt:
          long_name_sv: "Akademi för Ledarskap och Teologi"
          long_name_en: "Academy for Leadership and Theology"
        bth:
          long_name_sv: "Blekinge tekniska högskola"
          long_name_en: "Blekinge Institute of Technology"
        cth:
          long_name_sv: "Chalmers tekniska högskola"
          long_name_en: "Chalmers University of Technology"
        ehs:
          long_name_sv: "Enskilda Högskolan Stockholm"
          long_name_en: "University College Stockholm"
        esh:
          long_name_sv: "Ersta Sköndal Bräcke högskola"
          long_name_en: "Ersta Sköndal Bräcke University College"
        fhs:
          long_name_sv: "Försvarshögskolan"
          long_name_en: "Swedish Defence University"
        ghi:
          long_name_sv: "Gymnastik- och idrottshögskolan"
          long_name_en: "Swedish School of Sport and Health Sciences"
        gu:
          long_name_sv: "Göteborgs universitet"
          long_name_en: "University of Gothenburg"
        hda:
          long_name_sv: "Högskolan Dalarna"
          long_name_en: "Dalarna University"
        hb:
          long_name_sv: "Högskolan i Borås"
          long_name_en: "University of Borås"
        hig:
          long_name_sv: "Högskolan i Gävle"
          long_name_en: "University of Gävle"
        hh:
          long_name_sv: "Högskolan i Halmstad"
          long_name_en: "Halmstad University"
        hs:
          long_name_sv: "Högskolan i Skövde"
          long_name_en: "University of Skövde"
        hkr:
          long_name_sv: "Högskolan Kristianstad"
          long_name_en: "Kristianstad University"
        hv:
          long_name_sv: "Högskolan Väst"
          long_name_en: "University West"
        kau:
          long_name_sv: "Karlstads universitet"
          long_name_en: "Karlstad University"
        ki:
          long_name_sv: "Karolinska institutet"
          long_name_en: "Karolinska Institute"
        kf:
          long_name_sv: "Konstfack"
          long_name_en: "University of Arts, Crafts and Design"
        kkh:
          long_name_sv: "Kungliga Konsthögskolan"
          long_name_en: "Royal Institute of Art"
        kmh:
          long_name_sv: "Kungliga Musikhögskolan i Stockholm"
          long_name_en: "Royal College of Music in Stockholm"
        kth:
          long_name_sv: "Kungliga tekniska högskolan"
          long_name_en: "Royal Institute of Technology"
        jth:
          long_name_sv: "Johannelunds teologiska högskola"
          long_name_en: "Johannelund School of Theology"
        liu:
          long_name_sv: "Linköpings universitet"
          long_name_en: "Linköping University"
        lnu:
          long_name_sv: "Linnéuniversitetet"
          long_name_en: "Linnaeus University"
        ltu:
          long_name_sv: "Luleå tekniska universitet"
          long_name_en: "Luleå University of Technology"
        lu:
          long_name_sv: "Lunds universitet"
          long_name_en: "Lund University"
        mau:
          long_name_sv: "Malmö universitet"
          long_name_en: "Malmö university"
        miu:
          long_name_sv: "Mittuniversitetet"
          long_name_en: "Mid Sweden University"
        mdh:
          long_name_sv: "Mälardalens högskola"
          long_name_en: "Mälardalen University"
        ni:
          long_name_sv: "Newmaninstitutet"
          long_name_en: "Newman Institute University College"
        rkh:
          long_name_sv: "Röda Korsets högskola"
          long_name_en: "The Swedish Red Cross University College"
        shh:
          long_name_sv: "Sophiahemmet Högskola"
          long_name_en: "Sophiahemmet University"
        hj:
          long_name_sv: "Stiftelsen Högskolan i Jönköping"
          long_name_en: "Jönköping University"
        skh:
          long_name_sv: "Stockholms konstnärliga högskola"
          long_name_en: "Stockholm University of the Arts"
        su:
          long_name_sv: "Stockholms universitet"
          long_name_en: "Stockholm University"
        slu:
          long_name_sv: "Sveriges lantbruksuniversitet"
          long_name_en: "Swedish University of Agricultural Sciences"
        sh:
          long_name_sv: "Södertörns högskola"
          long_name_en: "Södertörn University"
        umu:
          long_name_sv: "Umeå universitet"
          long_name_en: "Umeå University"
        uu:
          long_name_sv: "Uppsala universitet"
          long_name_en: "Uppsala University"
        oru:
          long_name_sv: "Örebro universitet"
          long_name_en: "Örebro University"
      ladok:
        #url: https://api.integrationstest.ladok.se
        url: https://api.ladok.se
        certificate:
          folder: cert
        atom:
          periodicity: 60
      eduid:
        iam:
          url: https://api.dev.eduid.se/scim/test
      sunet:
        auth:
          url: https://auth-test.sunet.se
      redis:
        db: 3
        host: eduid_ladok_redis:6379
        sentinel_hosts:
        #  - localhost:1231
        #  - localhost:12313
        sentinel_service_name: redis-cluster
    x_service:
      api_server:
        host: 8080
