---
version: "3.9"

services:
  eduid_ladok:
    build:
      context: .
    image: eduid_ladok
    volumes:
      - eduid_ladok:/data
    command: bin/eduid_ladok
    networks:
      eduid_ladok-net:
        ipv4_address: 172.16.20.2

  redis:
    image: redis:alpine
    container_name: "redis"
    expose:
      - 6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      eduid_ladok-net:
        ipv4_address: 172.16.20.3


networks:
  eduid_ladok-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-eduid-ladok
    ipam:
      driver: default
      config:
        - subnet: 172.16.20.0/24
volumes:
    redis_data:
    eduid_ladok: