---
version: "3.9"

services:
  eduid_ladok:
    container_name: "eduid_ladok"
    build:
      context: .
    image: eduid_ladok
    volumes:
      - eduid_ladok:/data
    depends_on:
      - redis
    networks:
      eduid_ladok-net:
        ipv4_address: 172.16.20.2

  redis:
    image: redis:alpine
    container_name: "redis"
    expose:
      - 6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      eduid_ladok-net:
        ipv4_address: 172.16.20.3


networks:
  eduid_ladok-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-eduid-ladok
    ipam:
      driver: default
      config:
        - subnet: 172.16.20.0/24
volumes:
    redis_data:
    eduid_ladok:




#ENV LOGXI=* \
#    DEBUG=true \
#    HOST=":8080" \
#    SCHOOL_NAMES="kf,lnu" \
#    KF_SAML_NAME="student.konstfack.se" \
#    LNU_SAML_NAME="lnu.se" \
#    LADOK_URL="https://api.integrationstest.ladok.se" \
#    LADOK_ATOM_PERIODICITY="60" \
#    EDUID_IAM_URL="https://api.dev.eduid.se/scim/test" \
#    JWT_URL="https://auth-test.sunet.se" \
#    LADOK_CERTIFICATE_FOLDER="cert" \
#    REDIS_ADDR="redis:6379" \
#    REDIS_DB="3"