---
version: "3"

services:
  eduid_ladok:
    container_name: "eduid_ladok"
    image: docker.sunet.se/eduid/eduid_ladok:latest
    healthcheck:
      test: curl --fail http://eduid_ladok:8080/health || exit 1
      interval: 20s
      retries: 5
      timeout: 10s
    volumes:
      - eduid_ladok:/data
      - ./cert:/cert:ro
      - ./dev-config-docker.yaml:/config.yaml:ro
    depends_on:
      - redis
    networks:
      - eduid_ladok-net
    environment:
      - "EDUID_CONFIG_YAML=config.yaml"
      - "HTTP_PROXY=haproxy:8080"

  #dev_docker:
  #  container_name: "dev_docker"
  #  build:
  #    context: ./dev_docker
  #  image: dev_docker:latest
  #  networks:
  #    eduid_ladok-net:
  #      ipv4_address: 172.16.40.3

  redis:
    image: redis:alpine
    container_name: "eduid_ladok_redis"
    expose:
      - 6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - eduid_ladok-net

networks:
  eduid_ladok-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-eduid-ladok
    ipam:
      driver: default
      config:
        - subnet: 172.16.40.0/24

volumes:
  redis_data:
  eduid_ladok:
  haproxy_control:
